site_name: 计算机组成原理实验（2022春季） | 哈工大（深圳）
copyright: 'Copyright &copy; 2020 - 2023 哈尔滨工业大学（深圳）'
repo_name: 'HITSZ-COMP2008'
repo_url: 'https://gitee.com/hitsz-cslab/organ'

markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  # - mathjaxhelper.js

theme:
  language: 'zh'
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  # favicon: assets/favicon.svg
  icon:
    logo: fontawesome/solid/computer
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: 'default'
      primary: 'orange'
      accent: 'orange'
      toggle:
        icon: material/weather-sunny
        name: 切换到夜晚模式
    - scheme: 'slate'
      primary: 'orange'
      accent: 'orange'
      toggle:
        icon: material/weather-night
        name: 切换到白天模式

nav:
  - 实验须知: 
    - 实验介绍: index.md
    - Verilog语法回顾: 
      - 初学Verilog的几点提醒: home/verilog/part0.md
      - 模块的基本结构: home/verilog/part1.md
      - 标识符和数据类型: home/verilog/part2.md
      - 运算符及表达式: home/verilog/part3.md
      - 逻辑门的描述: home/verilog/part4.md
      - 赋值语句和块语句: home/verilog/part5.md
      - 条件语句和循环语句: home/verilog/part6.md
      - 宏定义和参数: home/verilog/defparam.md
      - 模块的实例化: home/verilog/part7.md
      - 模块的测试: home/verilog/module_test.md
      - 4位全加器设计实例: home/verilog/part8.md
    - 实验提交说明: home/operation.md
  - 从C语言到机器码: 
    - 实验平台: lab1/part1.md
    - 实验目的: lab1/part2.md
    - 实验原理: lab1/part4.md
    - 实验准备: lab1/part5.md
    - 实验内容: lab1/part3.md
    - 实验提交: lab1/part6.md
    - 附录:
      - 实验环境安装提示: lab1/error.md
      - Ubuntu常用命令: lab1/appdix.md
      - Vim常用指令: lab1/vim.md
      - Text Editor: lab1/text.md
  - 十进制转十六进制: 
    - 实验平台: lab2/part1.md
    - 实验目的: lab2/part2.md
    - 实验内容: lab2/part3.md
    - 实验原理: lab2/part4.md
    - 实验提交: lab2/part5.md
  - Booth乘法器设计:
    - 实验平台: lab3/part1.md
    - 实验目的: lab3/part2.md
    - 实验内容: lab3/part3.md
    - 实验原理: lab3/part4.md
    - 实验准备: lab3/part5.md
    - 实验提交: lab3/part6.md
  - 直接映射Cache设计:
    - 实验概述: lab4/part1.md
    - 实验原理: lab4/part4.md
    - 实验步骤: lab4/part6.md
    - 实验提交: lab4/part7.md